export const translations = {
  en: { language: 'English', signIn: 'Sign in', email: 'EMAIL', password: 'PASSWORD', home: 'Home', recipes: 'Recipes', planner: 'Planner', shopping: 'Shopping list', profile: 'Profile', planWeek: 'Plan your week', searchRecipes: 'Search your recipes', dietary: 'Dietary preferences', allergies: 'Allergies & ingredients', reminders: 'Reminders', darkMode: 'Dark mode', privacy: 'Privacy & terms', language: 'Language', chooseLanguage: 'Choose your language', socialGoogle: 'Continue with Google', socialApple: 'Continue with Apple', missingDetails: 'Enter your email and password.', authFailed: 'Check your connection and try again.' },
  ur: { language: 'اردو', signIn: 'سائن اِن', email: 'ای میل', password: 'پاس ورڈ', home: 'ہوم', recipes: 'ترکیبیں', planner: 'منصوبہ', shopping: 'خریداری فہرست', profile: 'پروفائل', planWeek: 'اپنے ہفتے کی منصوبہ بندی کریں', searchRecipes: 'اپنی ترکیبیں تلاش کریں', dietary: 'غذائی ترجیحات', allergies: 'الرجی اور اجزاء', reminders: 'یاد دہانیاں', darkMode: 'ڈارک موڈ', privacy: 'رازداری اور شرائط', language: 'زبان', chooseLanguage: 'اپنی زبان منتخب کریں', socialGoogle: 'گوگل کے ساتھ جاری رکھیں', socialApple: 'ایپل کے ساتھ جاری رکھیں', missingDetails: 'اپنی ای میل اور پاس ورڈ درج کریں۔', authFailed: 'کنکشن چیک کریں اور دوبارہ کوشش کریں۔' },
  ar: { language: 'العربية', signIn: 'تسجيل الدخول', email: 'البريد الإلكتروني', password: 'كلمة المرور', home: 'الرئيسية', recipes: 'الوصفات', planner: 'المخطط', shopping: 'قائمة التسوق', profile: 'الملف الشخصي', planWeek: 'خطط لأسبوعك', searchRecipes: 'ابحث عن وصفاتك', dietary: 'التفضيلات الغذائية', allergies: 'الحساسيات والمكونات', reminders: 'التذكيرات', darkMode: 'الوضع الداكن', privacy: 'الخصوصية والشروط', language: 'اللغة', chooseLanguage: 'اختر لغتك', socialGoogle: 'المتابعة مع Google', socialApple: 'المتابعة مع Apple', missingDetails: 'أدخل بريدك الإلكتروني وكلمة المرور.', authFailed: 'تحقق من الاتصال وحاول مرة أخرى.' },
  fr: { language: 'Français', signIn: 'Se connecter', email: 'E-MAIL', password: 'MOT DE PASSE', home: 'Accueil', recipes: 'Recettes', planner: 'Planning', shopping: 'Courses', profile: 'Profil', planWeek: 'Planifiez votre semaine', searchRecipes: 'Rechercher vos recettes', dietary: 'Préférences alimentaires', allergies: 'Allergies et ingrédients', reminders: 'Rappels', darkMode: 'Mode sombre', privacy: 'Confidentialité et conditions', language: 'Langue', chooseLanguage: 'Choisissez votre langue', socialGoogle: 'Continuer avec Google', socialApple: 'Continuer avec Apple', missingDetails: 'Saisissez votre e-mail et votre mot de passe.', authFailed: 'Vérifiez votre connexion et réessayez.' },
  es: { language: 'Español', signIn: 'Iniciar sesión', email: 'CORREO', password: 'CONTRASEÑA', home: 'Inicio', recipes: 'Recetas', planner: 'Planificador', shopping: 'Compras', profile: 'Perfil', planWeek: 'Planifica tu semana', searchRecipes: 'Buscar tus recetas', dietary: 'Preferencias dietéticas', allergies: 'Alergias e ingredientes', reminders: 'Recordatorios', darkMode: 'Modo oscuro', privacy: 'Privacidad y condiciones', language: 'Idioma', chooseLanguage: 'Elige tu idioma', socialGoogle: 'Continuar con Google', socialApple: 'Continuar con Apple', missingDetails: 'Introduce tu correo y contraseña.', authFailed: 'Comprueba la conexión e inténtalo de nuevo.' },
  zh: { language: '中文', signIn: '登录', email: '电子邮件', password: '密码', home: '首页', recipes: '食谱', planner: '计划', shopping: '购物清单', profile: '个人资料', planWeek: '规划一周', searchRecipes: '搜索食谱', dietary: '饮食偏好', allergies: '过敏与食材', reminders: '提醒', darkMode: '深色模式', privacy: '隐私与条款', language: '语言', chooseLanguage: '选择语言', socialGoogle: '使用 Google 继续', socialApple: '使用 Apple 继续', missingDetails: '请输入电子邮件和密码。', authFailed: '请检查网络连接后重试。' },
} as const;
export type Language = keyof typeof translations;
export const rtlLanguages: Language[] = ['ur', 'ar'];
